name: replay-plugin
version: '${project.version}'
main: me.lagggpixel.replay.Replay
authors: [lagggpixel, Kiiya, agentnoobff]
softdepend: [ PlaceholderAPI ]
commands:
  replay:
    description: Open the replays menu
  startrecording:
    description: Starts recording the current world
  stoprecording:
    description: Stops recording the current world
